#!/bin/bash

set -e

exec "$SNAP/bin/gunicorn" --chdir "$SNAP/django-app" \
    --bind unix:/tmp/django-gunicorn.sock myproj.wsgi \
    --error-logfile "$SNAP_COMMON/log/gunicorn-error.log" \
    --access-logfile "$SNAP_COMMON/log/gunicorn-access.log" "$@"
