name: django-gunicorn-nginx
version: '0.1' 
summary: django-gunicorn-nginx
description: |
  Django-Gunicorn-NGINX Example

grade: stable
confinement: classic

apps:

  django-gunicorn:
    daemon: simple
    plugs: [network-bind]
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      PYTHONPATH: $SNAP/lib/python3.6/site-packages/
      DJANGO_SECRETS_DIR: $SNAP_COMMON/django_secrets
    command: wrappers/django-gunicorn

  django-manage:
    plugs: [network-bind]
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      PYTHONPATH: $SNAP/lib/python3.6/site-packages/
      DJANGO_SECRETS_DIR: $SNAP_COMMON/django_secrets
    command: wrappers/django-manage

  nginx:
    daemon: simple
    plugs: [network-bind]
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    command: wrappers/nginx-run
    reload-command: wrappers/nginx-reload


parts:

  django-gunicorn:
    plugin: python
    source: .
    python-version: python3
    requirements: requirements/requirements.txt
    stage-packages:
      - libpq-dev
      - libssl-dev
      - libjpeg-dev
      - libc6-dev
      - libc6
    build-packages:
      - libc6-dev
      - libc6
    prime:
      - -.venv
      - -venv
      - -env
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/django_app
      python3.6 ./manage.py collectstatic --no-input
      cp -r ./* $SNAPCRAFT_PART_INSTALL/django_app/

  wrappers:
    plugin: dump
    source: snap/wrap/

  nginx:
    plugin: nginx
    source: snap/templates/
    stage-packages:
      - libc6-dev
      - libc6
    build-packages:
      - libc6-dev
      - libc6
    override-build: |
      rm $SNAPCRAFT_PART_INSTALL/nginx/conf/nginx.conf.default
      rm $SNAPCRAFT_PART_INSTALL/nginx/conf/nginx.conf
      mv ./nginx.conf.snap.template $SNAPCRAFT_PART_INSTALL/nginx/conf/nginx.conf
